# Generated by Django 6.1 on 2026-09-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_notification_category_notification_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedprocess',
            name='version_at_save',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
