# Generated by Django 6.1 on 2026-09-03 07:39

import apps.dashboard.models
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_savedprocess_version_at_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/sambhavacharya/Developer/bisup/hamronepal.com/private_media')), upload_to=apps.dashboard.models.document_upload_path),
        ),
    ]
