# Generated by Django 5.1.15 on 2026-09-07 14:37

import apps.core.validators
import apps.dashboard.models
import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userdocument_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/sambhavacharya/Developer/bisup/hamronepal.com/private_media')), upload_to=apps.dashboard.models.document_upload_path, validators=[apps.core.validators.validate_image_file_size]),
        ),
    ]
