# Generated by Django 6.1 on 2026-09-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
