# Generated by Django 5.1.15 on 2026-09-03 15:20

from django.db import migrations, models


def rename_ne_to_np(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(preferred_language='ne').update(preferred_language='np')


def rename_np_to_ne(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(preferred_language='np').update(preferred_language='ne')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('np', 'नेपाली')], default='en', max_length=2),
        ),
        migrations.RunPython(rename_ne_to_np, rename_np_to_ne),
    ]
