# Generated by Django 5.1.15 on 2026-09-07 14:37

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_terms_accepted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[apps.core.validators.validate_image_file_size]),
        ),
    ]
