# Generated by Django 6.1 on 2026-09-01 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'process categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('estimated_duration_min_days', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_duration_max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_duration_note', models.CharField(blank=True, max_length=255)),
                ('total_fee_note', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('last_verified_at', models.DateField(blank=True, null=True)),
                ('current_version_number', models.CharField(blank=True, max_length=20)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('last_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_processes', to=settings.AUTH_USER_MODEL)),
                ('responsible_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processes', to='organizations.governmentorganization')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='processes.processcategory')),
            ],
            options={
                'verbose_name_plural': 'processes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProcessSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('url', models.URLField()),
                ('last_verified_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_sources', to='organizations.governmentorganization')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='processes.process')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_verified_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('variant', models.CharField(choices=[('all', 'All'), ('individual', 'Individual'), ('business', 'Business')], default='all', max_length=20)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_note', models.CharField(blank=True, max_length=255)),
                ('estimated_duration_note', models.CharField(blank=True, max_length=255)),
                ('is_optional', models.BooleanField(default=False)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_steps', to='organizations.governmentoffice')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='processes.process')),
            ],
            options={
                'ordering': ['process', 'order'],
                'unique_together': {('process', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProcessRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('variant', models.CharField(choices=[('all', 'All'), ('individual', 'Individual'), ('business', 'Business')], default='all', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='processes.process')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='processes.processstep')),
            ],
            options={
                'ordering': ['process', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.CharField(max_length=20)),
                ('snapshot', models.JSONField()),
                ('changelog', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='processes.process')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_process_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
                'unique_together': {('process', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='UserProcessProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_selected', models.CharField(blank=True, choices=[('all', 'All'), ('individual', 'Individual'), ('business', 'Business')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('preparing', 'Preparing'), ('applied', 'Applied'), ('processing', 'Processing'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='processes.process')),
                ('process_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_progress', to='processes.processversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user process progress',
                'unique_together': {('user', 'process')},
            },
        ),
        migrations.CreateModel(
            name='UserRequirementProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_progress', to='processes.userprocessprogress')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='processes.processrequirement')),
            ],
            options={
                'verbose_name_plural': 'user requirement progress',
                'unique_together': {('progress', 'requirement')},
            },
        ),
        migrations.CreateModel(
            name='UserStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='processes.userprocessprogress')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='processes.processstep')),
            ],
            options={
                'verbose_name_plural': 'user step progress',
                'unique_together': {('progress', 'step')},
            },
        ),
    ]
