# Generated by Django 6.1 on 2026-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='description_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='eligibility_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='eligibility_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='estimated_duration_note_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='estimated_duration_note_ne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='meta_description_ne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='meta_title_ne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='summary_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='title_en',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='title_ne',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='total_fee_note_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='total_fee_note_ne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processcategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processcategory',
            name='description_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processcategory',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='processcategory',
            name='name_ne',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='processrequirement',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processrequirement',
            name='description_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processrequirement',
            name='name_en',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='processrequirement',
            name='name_ne',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='description_ne',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='estimated_duration_note_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='estimated_duration_note_ne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='fee_note_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='fee_note_ne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='title_en',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='title_ne',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
