# Generated by Django 6.1 on 2026-09-01 14:43

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('processes', '0002_process_description_en_process_description_ne_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='search_vector_en',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='search_vector_ne',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='process',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_en'], name='processes_p_search__af08bf_gin'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_ne'], name='processes_p_search__57f24e_gin'),
        ),
    ]
