# Generated by Django 6.1 on 2026-09-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_process_search_vector_en_process_search_vector_ne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('question_en', models.CharField(max_length=255, null=True)),
                ('question_ne', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField()),
                ('answer_en', models.TextField(null=True)),
                ('answer_ne', models.TextField(null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='processes.process')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['process', 'order'],
            },
        ),
    ]
