# Generated by Django 5.1.15 on 2026-09-03 15:20

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('processes', '0005_processexperience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='process',
            name='processes_p_search__57f24e_gin',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='description_ne',
            new_name='description_np',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='eligibility_ne',
            new_name='eligibility_np',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='estimated_duration_note_ne',
            new_name='estimated_duration_note_np',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='meta_description_ne',
            new_name='meta_description_np',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='meta_title_ne',
            new_name='meta_title_np',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='search_vector_ne',
            new_name='search_vector_np',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='summary_ne',
            new_name='summary_np',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='title_ne',
            new_name='title_np',
        ),
        migrations.RenameField(
            model_name='process',
            old_name='total_fee_note_ne',
            new_name='total_fee_note_np',
        ),
        migrations.RenameField(
            model_name='processcategory',
            old_name='description_ne',
            new_name='description_np',
        ),
        migrations.RenameField(
            model_name='processcategory',
            old_name='name_ne',
            new_name='name_np',
        ),
        migrations.RenameField(
            model_name='processfaq',
            old_name='answer_ne',
            new_name='answer_np',
        ),
        migrations.RenameField(
            model_name='processfaq',
            old_name='question_ne',
            new_name='question_np',
        ),
        migrations.RenameField(
            model_name='processrequirement',
            old_name='description_ne',
            new_name='description_np',
        ),
        migrations.RenameField(
            model_name='processrequirement',
            old_name='name_ne',
            new_name='name_np',
        ),
        migrations.RenameField(
            model_name='processstep',
            old_name='description_ne',
            new_name='description_np',
        ),
        migrations.RenameField(
            model_name='processstep',
            old_name='estimated_duration_note_ne',
            new_name='estimated_duration_note_np',
        ),
        migrations.RenameField(
            model_name='processstep',
            old_name='fee_note_ne',
            new_name='fee_note_np',
        ),
        migrations.RenameField(
            model_name='processstep',
            old_name='title_ne',
            new_name='title_np',
        ),
        migrations.AddIndex(
            model_name='process',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector_np'], name='processes_p_search__1d4f40_gin'),
        ),
    ]
