# Generated by Django 5.1.15 on 2026-09-06 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0006_rename_ne_fields_to_np'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120, null=True)),
                ('name_np', models.CharField(max_length=120, null=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_np', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'destination categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('title_en', models.CharField(max_length=220, null=True)),
                ('title_np', models.CharField(max_length=220, null=True)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('region', models.CharField(max_length=120)),
                ('summary', models.TextField(blank=True)),
                ('summary_en', models.TextField(blank=True, null=True)),
                ('summary_np', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_np', models.TextField(blank=True, null=True)),
                ('highlights_intro', models.CharField(blank=True, max_length=255)),
                ('highlights_intro_en', models.CharField(blank=True, max_length=255, null=True)),
                ('highlights_intro_np', models.CharField(blank=True, max_length=255, null=True)),
                ('best_season', models.CharField(blank=True, choices=[('autumn', 'Autumn (Sep-Nov)'), ('winter', 'Winter (Dec-Feb)'), ('spring', 'Spring (Mar-May)'), ('monsoon', 'Monsoon (Jun-Aug)')], max_length=20)),
                ('budget_note', models.CharField(blank=True, max_length=255)),
                ('budget_note_en', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_note_np', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='destinations/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('source_note', models.CharField(blank=True, max_length=255)),
                ('last_verified_at', models.DateField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_title_np', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('meta_description_en', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description_np', models.CharField(blank=True, max_length=255, null=True)),
                ('related_processes', models.ManyToManyField(blank=True, related_name='tourism_destinations', to='processes.process')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinations', to='tourism.destinationcategory')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DestinationHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('activity', 'Thing to do'), ('food', 'Food & experience'), ('stay', 'Where to stay'), ('transport', 'Getting around')], default='activity', max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('title_en', models.CharField(max_length=220, null=True)),
                ('title_np', models.CharField(max_length=220, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_np', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tourism.destination')),
            ],
            options={
                'ordering': ['destination', 'kind', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('day_number', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stops', to='tourism.destination')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='tourism.trip')),
            ],
            options={
                'ordering': ['trip', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RecentlyViewedDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_by', to='tourism.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_viewed_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'recently viewed destinations',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='tourism.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'destination')},
            },
        ),
    ]
