# Generated by Django 5.1.15 on 2026-09-07 14:37

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, upload_to='destinations/', validators=[apps.core.validators.validate_image_file_size]),
        ),
    ]
