# Generated by Django 5.1.15 on 2026-09-08 04:24

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_alter_destination_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', validators=[apps.core.validators.validate_image_file_size]),
        ),
    ]
