# Generated by Django 5.1.15 on 2026-09-12 04:50

import apps.core.validators
import apps.tourism.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_destinationcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.tourism.models.destination_image_upload_path, validators=[apps.core.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='destinationcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.tourism.models.category_image_upload_path, validators=[apps.core.validators.validate_image_file_size]),
        ),
    ]
