# Generated by Django 6.1 on 2026-09-01 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('name_ne', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('type', models.CharField(choices=[('ministry', 'Ministry'), ('department', 'Department'), ('constitutional_body', 'Constitutional Body'), ('local_government', 'Local Government'), ('other', 'Other')], max_length=30)),
                ('website_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='organizations/logos/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('name_ne', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office_hours', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='government_offices', to='locations.municipality')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='government_offices', to='locations.ward')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='organizations.governmentorganization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
